### PR TITLE
Added empty state when no property results with text and clear filters button

### PR DESCRIPTION
**Pull request by Michael-Dratch**
This PR is for this task: Provide Empty state for when there are no results #664

To get to this empty state. Go to find properties page. Select both the "high" priority and "Buy Affordably from Owner" filters to get 0 results. Then exit out of the filters to see the new content. Click the "clear filters" button to remove the filters.

image

### CODE REVIEW

**Review by CodeWritingCow — CHANGES_REQUESTED** [review]
Hi @Michael-Dratch: I tested your PR, and the UI worked as expected.

The issue has another acceptance criterion — using `aria-live` region to announce the empty state to screen reader users. Can you add that to your PR? Thanks!

**Comment by Michael-Dratch** [comment]
Hi @CodeWritingCow. My bad, I got a little too excited to push the PR. I added the aria live region and now when a user selects a combination of filters that have no results and navigates back to the results pane, the screen reader reads the text "No Results. There are no results that match your filter. Clear filters." Let me know if this is the correct behavior or if any other changes need to be made for the screen reader behavior.

**Comment by CodeWritingCow** [comment]
> Hi @CodeWritingCow. My bad, I got a little too excited to push the PR. I added the aria live region and now when a user selects a combination of filters that have no results and navigates back to the results pane, the screen reader reads the text "No Results. There are no results that match your filter. Clear filters." Let me know if this is the correct behavior or if any other changes need to be made for the screen reader behavior.

Hi @Michael-Dratch, no worries! I'll test your updated PR now.

**Review by CodeWritingCow — APPROVED** [review]
@Michael-Dratch I tested your PR with VoiceOver on Mac. It read out the empty state. Thanks for contributing!

Screen Shot 2024-06-30 at 8 41 13 PM

**Comment by CodeWritingCow** [comment]
Hi @bacitracin can you take a quick look at this A11y PR in case I missed something? Thanks!

**Review by bacitracin — APPROVED** [review]

**Pull request merged**
