### PR TITLE
Fix Property List Controls - 594

### PR DESCRIPTION
**Pull request by AZBL**
This change fixes the styling of the property list controls on the Find Properties page. 

- It should now match prototype.
- It removes the bottom border line.
- Removes left padding from [number] properties in view from large screens so there should only be 24 px of padding now
- Keeps left padding for [number] properties in view for small and medium screens so there is an extra 16px of space (otherwise when it switches to 1 property property img per row and the download/filter buttons change to icons only the alignment looks off). I included how this looks with the extra padding and without the extra padding. 

With Extra Padding:
with_padding

Without Extra Padding:
without_padding

- Removes right padding from the Download button so there should only be 24 px of padding now

### CODE REVIEW

**Comment by thansidwell** [comment]
Hey @AZBL. Just one little issue and then it's all good. The hover background of the property cards' top padding gets cut off. Dropping it down like 8px or so would fix it. 

CleanShot 2024-04-30 at 00 09 35@2x

**Comment by AZBL** [comment]
@thansidwell 
I added 8 px of top margin to the div containing the Table so now the hover background does not get cut off.

**Review by thansidwell — APPROVED** [review]
Approved. @AZBL said he fixed the small issue I found.

**Comment by Moylena** [comment]
#594

**Pull request merged**
