### PR TITLE
Issue 660: Add aria label to IconLink

### LINKED ISSUE #660: Navigation: Update `aria-current` to `page`
## Description

Update the `<aria-current="true">` value to `page` for Navigation linked "Find Properties", "Get Access", "Transform" & "About", because it is more appropriate.

## Acceptance Criteria

Update `aria-current` value to `page` to the following items:
- [ ] Find Properties 
- [ ] Get Access
- [ ] Transform
- [ ] About

### PR DESCRIPTION
**Pull request by KenMain5**
Refactored the value of aria-current from "true" to "page" as the description requested. 

Closes #660

### CODE REVIEW

**Review by CodeWritingCow — APPROVED** [review]
Hi @KenMain5, PR looks good. I checked `aria-current` on the four pages. Its value is set to `page` as expected. Thanks for contributing!

**Comment by CodeWritingCow** [comment]
Hi @marvieqa @bacitracin can you take a quick look at this a11y-related PR? Thank you!

**Comment by bacitracin** [comment]
Hey @KenMain5 I haven't pulled down this branch and tested it yet, but it seems straightforward enough and @CodeWritingCow tested it. Had a question though.

`aria-current` is currently used in both the IconLink and ThemeButton components. This PR fixes the issue in Iconlink, but the title of the PR mentions ThemeButtonLink. Is the PR title just out of date or incorrect?

**Comment by KenMain5** [comment]
> Hey @KenMain5 I haven't pulled down this branch and tested it yet, but it seems straightforward enough and @CodeWritingCow tested it. Had a question though.
> 
> `aria-current` is currently used in both the IconLink and ThemeButton components. This PR fixes the issue in Iconlink, but the title of the PR mentions ThemeButtonLink. Is the PR title just out of date or incorrect?

**Comment by KenMain5** [comment]
@bacitracin that's my mb! yes yes, the PR title is incorrect but the code fixes the correct issue 660

**Review by bacitracin — APPROVED** [review]

**Comment by CodeWritingCow** [comment]
@bacitracin thanks for catching the PR title mistake. I've fixed the title.

**Pull request merged**
