### PR TITLE
fix donate option not visible in mobile nav dropdown

### LINKED ISSUE #976: Mobile nav - Donate option is not visible in dropdown
**Describe the bug**
On narrow screens the navigation switches to the hamburger menu and dropdown. The new Donate page is at the bottom of the nav, but you can't see it and can barely click on it with the. mouse.

**To Reproduce**

1. Click on "Donate" in the nav.
2. Narrow the width of the screen to get the nav to switch to the hamburger icon.
3. Click on the hamburger icon to trigger the nav dropdown to show

**Expected behavior**
You should be able to see the Donate option fully.

**Screenshots**
Screenshot 2024-10-27 at 12 02 15 AM

### PR DESCRIPTION
**Pull request by vinhyan**
# Description

The mobile nav dropdown currently overflows, causing some items to be hidden and requiring users to scroll to view all options. This PR adjusts the `max-height` of the mobile nav dropdown, ensuring all items are fully visible without scrolling.

Fixes #976 

https://github.com/user-attachments/assets/037c6f31-293c-41f2-be0b-06712f6de38b

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by CodeWritingCow** [comment]
Hello @vinhyan, I switched the target branch from `main` to `staging`. That is our project's practice for submitting most PRs (except for those deploying to the live site). Thanks!

**Comment by vinhyan** [comment]
Oh shoot sorry I overlooked that. Thank you @CodeWritingCow! :)

**Review by bacitracin — APPROVED** [review]
LGTM

**Comment by vinhyan** [comment]
Hi @bacitracin! Sorry for bothering you again but would you be able to add the `hacktoberfest` label to this PR?

**Comment by bacitracin** [comment]
@vinhyan done!

**Pull request merged**
