### PR TITLE
Feat #599: Improve map toggle 

### PR DESCRIPTION
**Pull request by amyyeung17**
## Description
This PR addresses issue #599.

## Testing/Proof

https://github.com/CodeForPhilly/clean-and-green-philly/assets/28910543/444aac9a-5c32-4c93-becc-4f4cbdf5fe93

### CODE REVIEW

**Comment by nlebovits** [comment]
@amyyeung17 is this still a draft PR, or can it be merged?

**Comment by amyyeung17** [comment]
@nlebovits @paulhchoi Unfortunately no. It's still blocked by #598.

**Comment by Moylena** [comment]
This should be done - @nlebovits  @thansidwell please approve

**Comment by amyyeung17** [comment]
@Moylena Oh sorry, I just noticed that the dependent PR was approved. I'll get onto this right away.

**Pull request merged**
