### PR TITLE
Fixes Styling Issues Within Header

### PR DESCRIPTION
**Pull request by DonovanAndrews300**
## **Description**
This PR introduces changes in the spacing and layout of the navbar items to achieve better alignment. Addresses [(Issue#1020)](https://github.com/CodeForPhilly/clean-and-green-philly/issues/1020#issuecomment-2543431067) 

---

## **Steps to Test**

1. You should be able to see the header upon loading the app.
2. The style changes should be in-line with what's mentioned in the original issue.
3. The styling should be consistent across selected and hover states.

---

### CODE REVIEW

**Comment by nlebovits** [comment]
@CodeWritingCow can we get a PR review?

**Comment by CodeWritingCow** [comment]
Hi @DonovanAndrews300 the icons look correct on desktop view.

How UI looks on current website:
Screen Shot 2024-12-27 at 3 34 07 PM

How it looks with PR:
Screen Shot 2024-12-27 at 3 34 18 PM


However, they look misaligned on mobile view.

How UI looks on current website:
Screen Shot 2024-12-27 at 3 37 26 PM

How it looks with PR:
Screen Shot 2024-12-27 at 3 37 37 PM

**Review by CodeWritingCow — CHANGES_REQUESTED** [review]
Hi @DonovanAndrews300 can you fix the alignment in mobile view? Once that's fixed, I'll approve the PR. Thanks!

**Review by CodeWritingCow — APPROVED** [review]
@DonovanAndrews300 PR looks good. Alignment in mobile view has been fixed. Thank you!

**Pull request merged**
