### PR TITLE
Fix gun violence graph in WHCM.

### LINKED ISSUE #747: A11y: Windows High Contrast Mode - Home page - gun violence graph
## Describe the bug
1. When in Windows High Contrast Mode / dark the labels on the gun violence graph are hard to see. 
Things that are not visible:
- Title - Annual Shootings in Philadelphia 2015 - 2023
- The x & y axis labels
- The "Fatal" and "non-fatal" text labels
- "Source: Philadelphia Police Department"

Normal
Screenshot 2024-07-15 at 10 27 10 AM

High Contrast Mode
Screenshot 2024-07-15 at 10 26 34 AM

You can fix this either by fixing the contrast of the text against the background, or you can set the background of the image to always be white. If you choose to go the first route (ideal), check out this article on WHCM special keywords (`Canvas` for background, `CanvasText` for labels, etc.) https://www.smashingmagazine.com/2022/03/windows-high-contrast-colors-mode-css-custom-properties/

## Acceptance Criteria
Open the page in WHCM dark or simulate it using Devtools(see link below)
- [ ] The labels will be visible against the background.

## Additional context
* https://www.smashingmagazine.com/2022/06/guide-windows-high-contrast-mode/
* How to simulate WHCM in Chrome Devtools - https://devtoolstips.org/tips/en/emulate-forced-colors/
*  https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/

### PR DESCRIPTION
**Pull request by zheyichn**
- Fixed gun violence graph in WHCM by setting image background color to be `white`.
- Note that a padding (5px) was added to the image styling; otherwise, the text would be oddly close to the image boundary. This adjustment also applies to other graphs on this page. Is this acceptable? @CodeWritingCow @bacitracin 

Screenshoots:
gun-graph-dark
---
gun-graph-light
---
Other graphs also have paddings in WHCM.
padding-added

Closes #747

### CODE REVIEW

**Comment by CodeWritingCow** [comment]
Hi @zheyichn can you pull in the latest code from `staging` branch? It will fix the problem with Vercel's deployment failure. Once you update this PR with that code, I'll review your PR. Thanks!

**Review by bacitracin — APPROVED** [review]
LGTM! The padding added in WHCM is fine, could be considered an improvement really. You just need to pull in the new code from staging to fix the Vercel deploy like @CodeWritingCow mentioned

**Comment by zheyichn** [comment]
Fixed! @CodeWritingCow

**Review by CodeWritingCow — APPROVED** [review]
@zheyichn PR looks good!

**Pull request merged**
