### PR TITLE
Azbl/665 Make Before and After Text on Image Actual Text

### PR DESCRIPTION
**Pull request by AZBL**
This addresses issue #665 and builds off previous PR #721 (which was closed after inactivity).

1. Replaces beforeAfter.png that included "Before" and "After" as part of the image to one that doesn't include this. 
2.  Compressed the image  reducing size by 72%. 
3. Added aria-labelledby to the Image component.
4. Added caption: "A Philadelphia lot before a clean up and the same lot, filled with trees and greenery after a clean up." in a p tag.
5. Ensured no large gap between caption and image by removing gap on container div.
6. Made caption text regular font weight  (was bold).

### CODE REVIEW

**Comment by AZBL** [comment]
@bacitracin @CodeWritingCow @marvieqa

**Review by CodeWritingCow — APPROVED** [review]
Hi @AZBL, updated image and caption look good on mobile and desktop. Thanks!

### Desktop
Screen Shot 2024-09-23 at 11 59 30 PM

### Mobile
Screen Shot 2024-09-23 at 11 59 55 PM

**Comment by CodeWritingCow** [comment]
@AZBL The compressed image looks the same as the original image, yet its file size is much smaller. That's awesome! What tool did you use for the image compression?

**Comment by AZBL** [comment]
> @AZBL The compressed image looks the same as the original image, yet its file size is much smaller. That's awesome! What tool did you use for the image compression?

@CodeWritingCow I used tinypng.com to compress it. I actually did it originally because I kept getting this error when I tried to push, 
```
error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
send-pack: unexpected disconnect while reading sideband packet
```

but compressing it still didn't work, so I entered
```
git config http.postBuffer 524288000
```
and pushed again and it worked.

**Review by CodeWritingCow — APPROVED** [review]

**Pull request merged**
