### PR TITLE
597: Accept or Decline Cookies

### LINKED ISSUE #597: Accept or Decline Cookies
People need a way to 

- Save properties to a list (in development)
- Preserve the filters (not yet built)
  - So when you click on a Get Access option and go back you don't have to enter your filters manually again. 
- Preserve their location and zoom level on the map
  - So when you go to another page and come back to the map you return to where you were

We decided that the best way to do that is with cookies. However we also need to 

- Let users know we are saving cookies into their browser
- Give them an option to decline
- If they decline, show them they need to accept it to use certain features

Here's the experience broken down. 

### Banner
- When users go to the website a banner appears at the bottom of the viewport fixed to the bottom. 
  - Add a blue background, heading, description, decline button and accept button matching the [prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=6687%3A49263&mode=design&t=N70QHaaNsyW7ez2E-1).
  - The banner should appear on every page you visit. 
- When you click "Accept"
  - The banner will disappear
  - We can then store cookies to their browser. 
- Clicking "Decline" 
  - The banner will disappear
  - We do not store cookies to their browser. Perhaps we should delete any cookies that we have saved to their browser at that moment. 

### Footer 
- On a footer there's a new "Cookie Settings" link 
- Rework the footer so all the elements are center aligned and seperated by "  —  "
  - When they are spread out they draw more attention to themselves than needed
- Clicking this will make the banner appear again so users can change their choice

### Save Button
- On a property, when a user clicks "Save" 
- If they have **_accepted_** cookies the property is saved as expected
- If they have **_declined_** cookies the banner appears again
- If they decline again the property does not save
- If they accept then the property is saved as expected 

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/bbb5c7c4-8fd2-48ca-925a-30ae64115a65

[View the Prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=6687%3A49263&mode=design&t=N70QHaaNsyW7ez2E-1)

### PR DESCRIPTION
**Pull request by CodeWritingCow**
## Description

This PR creates a cookie consent banner for users to accept or decline cookies in their Web browser.

When user declines cookies and then clicks the "Save Property" button, the property won't be saved. Instead, the cookie-consent banner will appear again and ask for their permission to save cookies in their browser.

Closes #597 

### Desktop view
Screen Shot 2024-05-28 at 11 46 42 PM

### Mobile view
Screen Shot 2024-05-28 at 11 45 44 PM

## Screen recordings

These videos show 3 of the scenarios where the cookie-consent banner will appear:

### 2) User clicks "Cookie Settings" in footer

https://github.com/CodeForPhilly/clean-and-green-philly/assets/7751862/fd3beb44-841e-4161-8b33-ca67efc229bc

### 3) User clicks "Save Property" button after declining cookies

https://github.com/CodeForPhilly/clean-and-green-philly/assets/7751862/0cafa75e-958b-4ce5-808e-fb1209d2fbaf

### CODE REVIEW

**Comment by nlebovits** [comment]
@thansidwell take a look?

**Comment by thansidwell** [comment]
@nlebovits How do I take a look? Usually there's a post with a Preview link.

**Comment by brandonfcohen1** [comment]
> @nlebovits How do I take a look? Usually there's a post with a Preview link.

I just approved the preview link, but @CodeWritingCow this is still a draft PR, is it ready for review?

**Comment by thansidwell** [comment]
Yeah, the cookie banner doesn't show up in the Preview.

**Comment by CodeWritingCow** [comment]
@brandonfcohen1 it's not ready for review yet. I've built a UI component for the banner. However, I still need to write the actual logic for allowing/disabling cookies.

**Comment by Moylena** [comment]
@thansidwell  @nlebovits  can you review and approve please?

**Comment by CodeWritingCow** [comment]
@bacitracin @thansidwell can you review this when you get a chance? Thank you!

**Pull request merged**
